// <auto-generated />
namespace WebApplication_musicstore_codefirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_createdby_field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_createdby_field));
        
        string IMigrationMetadata.Id
        {
            get { return "201702211149554_added_createdby_field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
